module.exports = {
  platform: "github",
  onboardingConfig: {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>platform-engineering-org/.github"
    ]
  },
  hostRules: [
    {
      "hostType": "docker",
      "matchHost": "docker.io",
      "username": process.env.DOCKER_HUB_USERNAME,
      "password": process.env.DOCKER_HUB_TOKEN
    }
  ],
  repositories: [
    "platform-engineering-org/.github",
    "platform-engineering-org/renovate-runner",
    "platform-engineering-org/bootstrap",
    "platform-engineering-org/helper",
    "platform-engineering-org/gitlab-runners",
    "platform-engineering-org/platform-engineering-org.github.io",
    "platform-engineering-org/gitlab-configuration",      
    "arcalot/arcaflow-plugin-wait",
    "arcalot/arcaflow-plugin-sdk-python",
    "arcalot/arcaflow-plugin-sdk-go",
    "arcalot/arcaflow-engine",
    "arcalot/arcaflow-lib-kubernetes-python",
    "arcalot/arcaflow-plugin-fio",
    "arcalot/arcaflow-plugin-sysbench",
    "arcalot/arcaflow-plugin-kubeconfig",
    "arcalot/arcaflow-plugin-metadata",
    "arcalot/arcaflow-plugin-minio",
    "arcalot/arcaflow-plugin-aws-ec2-control",
    "arcalot/arcaflow-plugin-elasticsearch",
    "arcalot/arcaflow-plugin-opensearch",
    "arcalot/arcaflow-engine-deployer-python",
    "arcalot/arcaflow-plugin-stressng",
    "arcalot/arcaflow-plugin-uperf",
    "arcalot/.github",
    "arcalot/arcaflow-plugin-smallfile",
    "arcalot/arcaflow-plugin-iperf3",
    "arcalot/arcaflow-plugin-utilities",
    "arcalot/arcaflow-plugin-pcp",
    "arcalot/arcaflow-plugin-template-python",
    "arcalot/arcaflow-plugin-example",
    "arcalot/arcaflow-docsgen",
    "arcalot/arcalot-round-table",
    "arcalot/arcaflow-plugin-baseimage-python",
    "arcalot/arcaflow-container-toolkit",
    "arcalot/arcaflow-container-toolkit-action",
    "arcalot/arcaflow-engine-deployer-kubernetes",
    "arcalot/arcaflow-engine-deployer-docker",
    "arcalot/arcaflow-engine-deployer-podman",
    "arcalot/arcaflow-engine-deployer",
    "arcalot/arcaflow-plugin-service",
    "arcalot/arcaflow-plugins-incubator",
    "arcalot/arcaflow-plugin-baremetal-ipmi-control",
    "arcalot/go-lang",
    "arcalot/log.arcalot.io",
    "arcalot/arcaflow-python",
    "crc-org/crc-cloud",
    "platform-engineering-org/renovate-test"
  ]
};


// "arcalot/go.flow.arcalot.io",
// "arcalot/arcaflow-workflows",
// "arcalot/go-assert",
// "arcalot/arcaflow-editor",
// "arcalot/doc.log.arcalot.io",
// "arcalot/arcalot.github.io",
// "arcalot/go-dgraph",
// "arcalot/arcalog",
// "arcalot/arcaflow-engine-deployer-test-impl",
// "arcalot/arcaflow-plugin-test-impl-go",
// "arcalot/arcaflow-lib-kubernetes-go",
// "arcalot/arcaflow-expressions",
// "arcalot/arcaflow-reusable-workflows",
// "arcalot/go.arcalot.io",
// "arcalot/arcalot.io-dns",
// "arcalot/go-log",
// "arcalot/arcaflow-plugin-opensearch-legacy",
// "arcalot/actions",
